"""WESF (Weather-Energy-Security Forecast) API endpoints."""
from __future__ import annotations

import structlog
from fastapi import APIRouter, HTTPException

from src.api.schemas import (
    CVIAlert,
    PipelineRunSummary,
    PriceForecast,
    RampAlertPayload,
)
from src.core.config import get_settings

logger = structlog.get_logger(__name__)

router = APIRouter()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_summary(run_id: str) -> PipelineRunSummary:
    """Load a PipelineRunSummary by run_id from the output directory."""
    settings = get_settings()
    summary_path = settings.data_output_dir / f"{run_id}_summary.json"
    if not summary_path.exists():
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found.")
    try:
        return PipelineRunSummary.model_validate_json(summary_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to parse summary: {exc}") from exc


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get(
    "/{run_id}/ramp-alerts",
    response_model=list[RampAlertPayload],
    summary="Get WESF ramp alerts for a run",
)
async def get_ramp_alerts(run_id: str) -> list[RampAlertPayload]:
    """
    Return all wind-turbine cut-out and solar-drop ramp alerts for the given run.

    Alerts are generated by the ``RampForecaster`` module during the pipeline run.
    An empty list indicates no threshold exceedances were detected.
    """
    summary = _load_summary(run_id)
    logger.info("wesf.ramp_alerts", run_id=run_id, count=len(summary.ramp_alerts))
    return summary.ramp_alerts


@router.get(
    "/{run_id}/cvi-alerts",
    response_model=list[CVIAlert],
    summary="Get Cyber Vulnerability Index alerts for a run",
)
async def get_cvi_alerts(run_id: str) -> list[CVIAlert]:
    """
    Return all CVI (Cyber Vulnerability Index) alerts for the given run.

    Alerts are generated by the ``CVIEngine`` module during the pipeline run.
    Each alert scores an asset's cyber risk on the 0–100 CVI scale.
    """
    summary = _load_summary(run_id)
    logger.info("wesf.cvi_alerts", run_id=run_id, count=len(summary.cvi_alerts))
    return summary.cvi_alerts


@router.get(
    "/{run_id}/price-forecast",
    response_model=PriceForecast,
    summary="Get electricity price forecast for a run",
)
async def get_price_forecast(run_id: str) -> PriceForecast:
    """
    Return the electricity price forecast for the given run.

    The forecast is generated by the N-BEATS price model and covers 24 hourly
    intervals from the pipeline run time. Includes negative-pricing flags.

    Raises 422 if no price forecast was generated for this run.
    """
    summary = _load_summary(run_id)
    if summary.price_forecast is None:
        raise HTTPException(
            status_code=422,
            detail=f"Run '{run_id}' has no price forecast (pipeline may have failed).",
        )
    logger.info("wesf.price_forecast", run_id=run_id, market=summary.price_forecast.market.value)
    return summary.price_forecast
